SUFFIX = _njs

modules:
	converter helpers.js $(SUFFIX)
	converter dataKeeper_new.js $(SUFFIX)
	converter block.js $(SUFFIX)
	converter sectionManager.js $(SUFFIX)

	mv helpers$(SUFFIX).js ../../
	mv dataKeeper_new$(SUFFIX).js ../../
	mv block$(SUFFIX).js ../../
	mv sectionManager$(SUFFIX).js ../../
