SUFFIX = _njs

modules:
	converter helpers.js $(SUFFIX)
	converter dataKeeper_2.js $(SUFFIX)
	converter dataKeeper.js $(SUFFIX)
	converter block.js $(SUFFIX)
	converter sectionManager.js $(SUFFIX)

	mv helpers$(SUFFIX).js ../../
	mv dataKeeper$(SUFFIX).js ../../
	mv dataKeeper_2$(SUFFIX).js ../../
	mv block$(SUFFIX).js ../../
	mv sectionManager$(SUFFIX).js ../../
