SUFFIX = _njs

modules:
	converter helpers.js $(SUFFIX)
	converter dataKeeper.js $(SUFFIX)
	converter block.js $(SUFFIX)
	converter sectionTools.js $(SUFFIX)

	mv helpers$(SUFFIX).js ../../
	mv dataKeeper$(SUFFIX).js ../../
	mv block$(SUFFIX).js ../../
	mv sectionTools$(SUFFIX).js ../../
